/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserDetail } from "./UserDetail";
import { UserDetailCountArgs } from "./UserDetailCountArgs";
import { UserDetailFindManyArgs } from "./UserDetailFindManyArgs";
import { UserDetailFindUniqueArgs } from "./UserDetailFindUniqueArgs";
import { CreateUserDetailArgs } from "./CreateUserDetailArgs";
import { UpdateUserDetailArgs } from "./UpdateUserDetailArgs";
import { DeleteUserDetailArgs } from "./DeleteUserDetailArgs";
import { UserAuthFindManyArgs } from "../../userAuth/base/UserAuthFindManyArgs";
import { UserAuth } from "../../userAuth/base/UserAuth";
import { UserDetailService } from "../userDetail.service";
@graphql.Resolver(() => UserDetail)
export class UserDetailResolverBase {
  constructor(protected readonly service: UserDetailService) {}

  async _userDetailsMeta(
    @graphql.Args() args: UserDetailCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserDetail])
  async userDetails(
    @graphql.Args() args: UserDetailFindManyArgs
  ): Promise<UserDetail[]> {
    return this.service.userDetails(args);
  }

  @graphql.Query(() => UserDetail, { nullable: true })
  async userDetail(
    @graphql.Args() args: UserDetailFindUniqueArgs
  ): Promise<UserDetail | null> {
    const result = await this.service.userDetail(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserDetail)
  async createUserDetail(
    @graphql.Args() args: CreateUserDetailArgs
  ): Promise<UserDetail> {
    return await this.service.createUserDetail({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => UserDetail)
  async updateUserDetail(
    @graphql.Args() args: UpdateUserDetailArgs
  ): Promise<UserDetail | null> {
    try {
      return await this.service.updateUserDetail({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserDetail)
  async deleteUserDetail(
    @graphql.Args() args: DeleteUserDetailArgs
  ): Promise<UserDetail | null> {
    try {
      return await this.service.deleteUserDetail(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [UserAuth], { name: "userId" })
  async findUserId(
    @graphql.Parent() parent: UserDetail,
    @graphql.Args() args: UserAuthFindManyArgs
  ): Promise<UserAuth[]> {
    const results = await this.service.findUserId(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
